version: '3.8'

services:
    mlflow-db:
        image: postgres:14.3
        environment:
            POSTGRES_DB: mlflowdb
            POSTGRES_USER: mlflow
            POSTGRES_PASSWORD: password
        ports:
            - "5436:5432"

    mlflow-server:
        build:
            context: ./dockerfiles/
            dockerfile: Dockerfile.server
        container_name: mlflow_server
        ports:
            - "8000:8000"
        command: mlflow server --host 0.0.0.0:8000 --backend-store-uri postgresql://mlflow:password@mlflow-db:5432/mlflowdb #--default-artifact-root s3://test-bucket/